### ISSUE TITLE
Some errors 

### ISSUE THREAD

**Issue by KevinHu2014** [kprimice/react-native-sensor-manager#10]
`sensormanager/LightSensorRecord.java:39: error: cannot find symbol
        if ((mLightSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_LIGHT)) != nul) {
                                                                                   ^
  symbol:   variable nul
  location: class LightSensorRecord
1 error`
==>missing l for null
`sensormanager/SensorManagerModule.java:137: error: missing return statement
    }
    ^
1 error`
==>
`public int stopLightSensor() {
      if(mLightSensorRecord != null)
        mLightSensorRecord.stop();
    }`this should be void

**Comment by kprimice** [comment]
Thanks, you can submit a PR. Or I'll do it asap
