### ISSUE TITLE
mSensorManager undefined

### ISSUE THREAD

**Issue by mileung** [kprimice/react-native-sensor-manager#14]
`var mSensorManager = require('NativeModules').SensorManager;
`
NativeModules does not have a `SensorManager` key.

When I console.log the keys of NativeModules, I get the following values: 
`
["FrescoModule", "DeviceEventManager", "AndroidConstants", "IntentAndroid", "AsyncSQLiteDBStorage", "DebugComponentOwnershipModule", "ImageLoader", "DialogManagerAndroid", "ToastAndroid", "AnimationsDebugModule", "Vibration", "LocationObserver", "NetInfo", "AndroidPermissions", "ImageStoreManager", "AppState", "JSCHeapCapture", "WebSocketModule", "StatusBarManager", "TimePickerAndroid", "Clipboard", "DatePickerAndroid", "Timing", "Networking", "CameraRollManager", "ExceptionsManager", "ImageEditingManager", "SourceCode", "UIManager"]`

**Comment by samhunta** [comment]
Check your `MainActivity.java` and check for the Sensor package

``` java
// File: MainActivity.java or MainApplication.java depending on RN version
package com.calcapp;

import com.facebook.react.ReactActivity;
import com.sensormanager.SensorManagerPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyApp";
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new SensorManagerPackage()
      );
    }
}
```

**Comment by mileung** [comment]
@samhunta https://github.com/kprimice/react-native-sensor-manager/issues/12

I posted that here.  Still not working for me.

**Comment by yf-hk** [comment]
See https://github.com/kprimice/react-native-sensor-manager/issues/12#issuecomment-245897907

**Comment by jaimecasero** [comment]
It maybe not related at all to the original issue, but in my case I didnt notice the build was not completely succesful when running "react-native run-android" command. So the java part of the application was not compiled,generating the "undefined" issue later at runtime. For the sake of completeness, i found my "build" issue was related to Windows OS directory permissions, preventing the build to be completed succesfully.
