### ISSUE TITLE
Appropriately use sampling rate?

### ISSUE THREAD

**Issue by rclai** [kprimice/react-native-sensor-manager#16]
According to [this](https://developer.android.com/reference/android/hardware/SensorManager.html#registerListener%28android.hardware.SensorEventListener, android.hardware.Sensor, int%29), you can specify in microseconds your sampling rate. That way you don't have to use your own manually rolled timing implementation.

It only requires API level 9 to be able to do this and React Native can only support 16+ I think.

**Comment by kprimice** [comment]
Yes you are right, the only concern I have is this comment:

>  This is only a hint to the system. Events may be received faster or slower than the specified rate. Usually events are received faster. 

How accurate is the delivered rate? How is it compared to the current implementation?

**Comment by rclai** [comment]
Oh, I didn't notice that statement. I haven't tried out its accuracy, but It's probably better to leave it as is because Android phones are so different from each other.
