### ISSUE TITLE
'Orientation'  API missing.

### ISSUE THREAD

**Issue by leibniz2** [kprimice/react-native-sensor-manager#21]
In the documentation, it stated that you could use `SensorManager.startOrientation(100)` , but it produced _'not a function'_ error. To make sure, I logged SensorManager, and it was not really there. 
Though, it was present in the source code atleast.

**Comment by kprimice** [comment]
The npm package was not updated. It should work now.

**Comment by leibniz2** [comment]
Thank you! Nice package by the way.
