### ISSUE TITLE
add method `start` for each sensor

### ISSUE THREAD

**Issue by zxcpoiu** [kprimice/react-native-sensor-manager#3]
Since not all sensors supported on any android versions, can we add a method `start()` which we register listener explicitly instead register directly in constructor.

We can detect [Sensor Availability](http://developer.android.com/guide/topics/sensors/sensors_overview.html#sensors-identify) in the constructor and show some warnings if sensor is not supported in this device.

I can help if you agree

**Comment by kprimice** [comment]
Good point!
I will look into it today if I have time. But you are welcome to submit a PR ;)

**Comment by zxcpoiu** [comment]
cool!

Let's do it, I will add a simple example in passing!

**Comment by zxcpoiu** [comment]
oh, by the way,

whether merged with react-native-motion-manager or not, do you think is it better to keep api consistency with the two?

maybe I can add new methods that correspond with `react-native-motion-manager` then after few versions bump deprecated the original one?

**Comment by kprimice** [comment]
I added your suggestions for the Magnetometer and Thermometer only for now. Tell me what you think.

**Comment by kprimice** [comment]
For now, let's not bother with react-native-motion-manager. I will contact the owner by the end of the day to see what we can do to merge. Indeed, it would be better to have consistency between the two!

**Comment by zxcpoiu** [comment]
wow, so fast!

ok, since I'm not familiar with Java, I will follow your pattern to complete the rest!

basically, I will do:
- add logs if the api doesn't support before `return (0)`
- complete the rest
- add new method name alias and keep the old one. ( both exists )

thanks for great job!

**Comment by kprimice** [comment]
I actually finished it for all of them. (I also tested it).

There is no need for keeping an old method: all the methods start_sensor_(int delay) now return an int. 0 is returned if the sensor is not found, 1 otherwise. So the usage is the same, but it is now possible to check whether the sensor exists or not.

Thank you so much for pointing this out!

**Comment by kprimice** [comment]
I will also add some real examples in the following days.

**Comment by zxcpoiu** [comment]
great!!!!!!!!!!!!!!!!!!!!!!!!!
