### ISSUE TITLE
How to reset step counter?

### ISSUE THREAD

**Issue by xiankai** [kprimice/react-native-sensor-manager#8]
I am pretty new to react native (and android/java) and was playing around with your package, but stopping/starting `StepCounterRecord` does not seem to affect the count in the slightest.

Is there a way to do this in the code? If not I may try looking deeper into the java code.

**Comment by kprimice** [comment]
Thank you for your message

As you can see here: https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_STEP_COUNTER
The step counter is only reset at reboot.
